/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ktc_media_scan_FileScannerJni */

#ifndef _Included_com_ktc_media_scan_FileScannerJni
#define _Included_com_ktc_media_scan_FileScannerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ktc_media_scan_FileScannerJni
 * Method:    scanFiles
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ktc_media_scan_FileScannerJni_scanFiles
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
