/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <dirent.h>
/* Header for class com_ktc_media_scan_FileScannerJni */

#ifndef _Included_com_ktc_media_scan_FileScannerJni
#define _Included_com_ktc_media_scan_FileScannerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ktc_media_scan_FileScannerJni
 * Method:    scanFiles
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ktc_media_scan_FileScannerJni_scanFiles
        (JNIEnv *, jclass, jstring);


void init(JNIEnv *pEnv);
void doScanFile(JNIEnv *env, jstring dirPath_);
void insertVideoData(JNIEnv *env,const char *dirPath, dirent *file, jobjectArray types, jint fileType);
jobject getGlobalContext(JNIEnv *env);

#ifdef __cplusplus
}
#endif
#endif
